# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: build
on:
  push:   # do not run when pushing tags
    branches:
      - '*'
jobs:

  ##############################################################################

  call_toolset_build:
    uses: ./.github/workflows/toolset_build.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: false
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}

  ##############################################################################

  call_toolset_validate:
    uses: ./.github/workflows/toolset_validate.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: false
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
    needs: call_toolset_build
