# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: build
on:
  push:   # do not run when pushing tags
    branches:
      - '*'

#
# This workflow builds the complete toolset and then builds Inkscape to
# verify everything works.
#

jobs:

  build:
    runs-on: macos-10.15
    env:
      WRK_DIR: /Users/Shared/work
      CCACHE_DIR: /Users/Shared/work/ccache
    steps:

    #--------------------------------------------------- prepare the environemnt

    - name: checkout mibap repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: create cache id
      id: cache_id
      uses: nanzm/get-time-action@v1.1
      with:
        format: "YYYY-MM-DD-HH-mm-ss"

    # Create a new cache, building ontop the most recent old one.
    - name: setup cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-toolset-${{ steps.cache_id.outputs.time }}
        restore-keys: ccache-toolset-

    # GitHub does not provide 10.13 SDK on their runners and no image older
    # than Catalina. See here for what you can expect in their Catalina image:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    #
    # Official downloads from Apple are not accessible without a developer
    # account and I don't trust 3rd party sources (e.g. "phracker"). So I'm
    # using my own (non-public) source, but I'm providing the means to verify
    # what I'm doing, see here:
    # https://github.com/dehesselle/sdkchecksum
    #
    # In order to use your custom SDK_DOWNLOAD_URL, create a repository secret
    # of said name and proivide a link to a .tar.xz file.
    # At the moment, only 10.13.4 SDK is supported (hardcoded below).
    - name: install macOS SDK
      if: env.SDK_DOWNLOAD_URL != null
      env:
        SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
      run: |
        mkdir -p $WRK_DIR
        curl -L ${{ secrets.SDK_DOWNLOAD_URL }} | tar -C $WRK_DIR -xJp
        echo "SDKROOT=$WRK_DIR/$(basename ${SDK_DOWNLOAD_URL%%.tar.xz*})" >> $GITHUB_ENV

    # Checkout repository to verify SDK...
    - name: checkout sdkchecksum repository
      if: env.SDK_DOWNLOAD_URL != null
      env:
        SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
      uses: actions/checkout@v2
      with:
        repository: dehesselle/sdkchecksum
        path: sdkchecksum
        clean: false

    # ...and use it to verify
    - name: verify SDK
      if: env.SDK_DOWNLOAD_URL != null
      env:
        SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
      run: |
        shasum -a 256 sdkchecksum/MacOSX10.13.4.sdk.sha256
        cd $WRK_DIR
        if shasum -s -c $GITHUB_WORKSPACE/sdkchecksum/MacOSX10.13.4.sdk.sha256; then
          echo "ok - SDK verified"
          exit 0
        else
          echo "error - SDK verification failed"
          exit 1
        fi

    # GitHub does not provide a clean macOS installation. We need to move the
    # pre-installed components out of the way so we don't pick them up by
    # accident.
    - name: disable /usr/local
      run: |
        cd /usr/local
        for dir in include lib share; do sudo mv $dir $dir.disabled; done

    #------------------------------------------------------------- build toolset

    - name: prepare system
      run: ./110-sysprep.sh

    - name: install JHBuild
      run: ./120-jhbuild_install.sh

    - name: bootstrap JHBuild
      run: ./130-jhbuild_bootstrap.sh

    - name: build GTK3 stack
      run: ./140-jhbuild_gtk3.sh

    - name: build Inkscape dependencies
      run: ./150-jhbuild_inkdeps.sh

    - name: install additional components
      run: ./160-jhbuild_other.sh

    - name: create toolset dmg
      id: toolset
      run: |
        source 010-init.sh
        toolset_create_dmg
        echo "::set-output name=version::$VERSION"

    #------------------------------------------------------------ build Inkscape

    - name: build Inkscape
      run: ./210-inkscape_build.sh

    - name: create Inkscape.app
      run: ./220-inkscape_package.sh

    - name: create Inkscape.dmg
      run: ./230-inkscape_distrib.sh

    #---------------------------------------------------------- upload artifacts

    # Restore /usr/local, GitHub actions depend on these.
    - name: restore /usr/local
      run: for dir in /usr/local/*.disabled; do sudo mv $dir ${dir/.disabled/}; done

    - name: upload toolset disk image
      uses: actions/upload-artifact@v2
      with:
        name: Inkscape_build_toolset
        path: ${{ github.workspace }}/mibap_v${{ steps.toolset.outputs.version }}.dmg

    - name: upload toolset checksum
      uses: actions/upload-artifact@v2
      with:
        name: Inkscape_build_toolset.sha256
        path: ${{ github.workspace }}/mibap_v${{ steps.toolset.outputs.version }}.dmg.sha256

    - name: upload Inkscape disk image
      uses: actions/upload-artifact@v2
      with:
        name: Inkscape_dmg
        path: ${{ github.workspace }}/Inkscape.dmg
