# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: build
on:
  push:   # do not run when pushing tags
    branches:
      - '*'
jobs:

  ##############################################################################

  build_dependencies:
    uses: ./.github/workflows/dependencies.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: false
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}

  ##############################################################################

  # Build Inkscape to validate the viability of the dependencies.
  build_inkscape:
    uses: ./.github/workflows/inkscape.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: false
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
    needs: build_dependencies
