# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: mibap
on: workflow_dispatch

# This workflow builds Inkscape using the latest release of mibap. You can
# set repository secrets for INK_URL and INK_BRANCH to instruct this workflow
# to build your custom fork and branch of Inkscape.

jobs:

  ##############################################################################

  inkscape:
    runs-on: macos-12
    env:
      WRK_DIR: /Users/Shared/work
      CCACHE_DIR: /Users/Shared/work/ccache
      INK_URL: ${{ secrets.INK_URL }}
      INK_BRANCH: ${{ secrets.INK_BRANCH }}
    steps:

      #------------------------------------------------- prepare the environment

      - name: Get latest release
        uses: oprypin/find-latest-tag@v1
        id: mibap
        with:
          repository: dehesselle/mibap
          releases-only: true

      - name: Checkout mibap repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.mibap.outputs.tag }}

      - name: Create timestamp
        id: timestamp
        uses: josStorer/get-current-time@v2
        with:
          format: "YYYY-MM-DD-HH-mm-ss"

      # Create a new cache, building ontop the most recent old one.
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-inkscape-${{ steps.timestamp.outputs.formattedTime }}
          restore-keys: ccache-inkscape-

      - name: Install dependencies
        run: ./install_toolset.sh

      # GitHub does not provide a clean macOS installation. We need to move the
      # pre-installed components out of the way so we don't pick them up by
      # accident.
      - name: Disable /usr/local
        run: |
          cd /usr/local
          for dir in include lib share; do sudo mv $dir $dir.disabled; done

      #---------------------------------------------------------- build Inkscape

      - name: Build Inkscape
        run: ./210-inkscape_build.sh

      - name: Create Inkscape application bundle
        run: ./220-inkscape_package.sh

      - name: Create Inkscape disk image
        run: ./230-inkscape_distrib.sh

      #------------------------------------------------ create Inkscape artifact

      # Restore /usr/local, GitHub actions depend on these.
      - name: Restore /usr/local
        run: for dir in /usr/local/*.disabled; do sudo mv $dir ${dir/.disabled/}; done

      - name: Upload Inkscape disk image
        uses: actions/upload-artifact@v3
        with:
          name: inkscape
          path: Inkscape*.dmg
