# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: release
on:
  push:   # only run for tags
    tags:
      - 'v*'
jobs:

  ##############################################################################

  check_prerequisites:
    runs-on: macos-12
    steps:

      - name: Checkout mibap repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fail on missing version tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed("version tag not found")

      - name: Get dependencies version
        id: dependencies
        env:
          SYS_USRLOCAL_IGNORE: true
        run: |
          source jhb/etc/jhb.conf.sh
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Ensure that the dependencies version (see above) matches the repository
      # version (from git tag).
      - name: Fail on version mismatch
        if: ${{ !endsWith(github.ref, steps.dependencies.outputs.version) }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed("version tag mismatch")

      - name: Fail on missing secret SDK_DOWNLOAD_URL
        if: env.SDK_DOWNLOAD_URL == null
        env:
          SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed("SDK_DOWNLOAD_URL secret not found")

  ##############################################################################

  build_dependencies:
    uses: ./.github/workflows/dependencies.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: true
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
    needs: check_prerequisites

  ##############################################################################

  # Build Inkscape to validate the viability of the dependencies.
  build_inkscape:
    uses: ./.github/workflows/inkscape.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: true
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
    needs: build_dependencies

  ##############################################################################

  create_release:
    runs-on: ubuntu-latest
    needs: build_inkscape
    steps:

      - name: Download dependencies disk image
        uses: actions/download-artifact@v4
        with:
          name: dependencies

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: mibap*.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
