# SPDX-FileCopyrightText: 2021 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: release
on:
  push:   # only run for tags
    tags:
      - 'v*'
jobs:

  ##############################################################################

  requirements_check:
    runs-on: macos-12
    steps:

      - name: Checkout mibap repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fail on missing version tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed("version tag not found")

      - name: Get toolset version
        id: toolset
        env:
          SYS_USRLOCAL_IGNORE: true
        run: |
          source jhb/etc/jhb.conf.sh
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get repository version tag
        id: repo
        run: echo "version=${GITHUB_REF##*v}" >> $GITHUB_OUTPUT

      # Once we have established that the "toolset version" (from jhb.conf.sh)
      # matches the "repo version" (from git tag) we can safely rely on
      # "repo version" from here on.
      - name: Fail on version mismatch
        if: ${{ !endsWith(github.ref, steps.toolset.outputs.version) }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed("version tag mismatch")

      - name: Fail on missing secret SDK_DOWNLOAD_URL
        if: env.SDK_DOWNLOAD_URL == null
        env:
          SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
        uses: actions/github-script@v3
        with:
          script: core.setFailed("SDK_DOWNLOAD_URL secret not found")

  ##############################################################################

  call_toolset_build:
    uses: ./.github/workflows/toolset_build.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: true
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
    needs: requirements_check

  ##############################################################################

  call_toolset_validate:
    uses: ./.github/workflows/toolset_validate.yml
    with:
      SDK_DOWNLOAD_URL_REQUIRED: true
    secrets:
      SDK_DOWNLOAD_URL: ${{ secrets.SDK_DOWNLOAD_URL }}
    needs: call_toolset_build

  ##############################################################################

  create_release:
    runs-on: macos-12
    needs: call_toolset_validate
    env:
      WRK_DIR: /Users/Shared/work
    steps:

      - name: Download toolset disk image
        uses: actions/download-artifact@v3
        with:
          name: Inkscape_build_toolset
          path: ${{ env.WRK_DIR }}/repo

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.WRK_DIR }}/repo/*.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
